/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrearDonacionRouteImport } from './routes/crear-donacion'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as EntregasRouteImport } from './routes/entregas'
import { Route as MisDonacionesRouteImport } from './routes/mis-donaciones'
import { Route as MisSolicitudesRouteImport } from './routes/mis-solicitudes'
import { Route as OrganizacionesRouteImport } from './routes/organizaciones'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as SolicitudesRouteImport } from './routes/solicitudes'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as DonacionesIndexRouteImport } from './routes/donaciones.index'
import { Route as DonacionesIdRouteImport } from './routes/donaciones.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearDonacionRoute = CrearDonacionRouteImport.update({
  id: '/crear-donacion',
  path: '/crear-donacion',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregasRoute = EntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => rootRouteImport,
} as any)
const MisDonacionesRoute = MisDonacionesRouteImport.update({
  id: '/mis-donaciones',
  path: '/mis-donaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const MisSolicitudesRoute = MisSolicitudesRouteImport.update({
  id: '/mis-solicitudes',
  path: '/mis-solicitudes',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizacionesRoute = OrganizacionesRouteImport.update({
  id: '/organizaciones',
  path: '/organizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitudesRoute = SolicitudesRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const DonacionesIndexRoute = DonacionesIndexRouteImport.update({
  id: '/donaciones/',
  path: '/donaciones/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonacionesIdRoute = DonacionesIdRouteImport.update({
  id: '/donaciones/$id',
  path: '/donaciones/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crear-donacion': typeof CrearDonacionRoute
  '/dashboard': typeof DashboardRoute
  '/empresas': typeof EmpresasRoute
  '/entregas': typeof EntregasRoute
  '/mis-donaciones': typeof MisDonacionesRoute
  '/mis-solicitudes': typeof MisSolicitudesRoute
  '/organizaciones': typeof OrganizacionesRoute
  '/perfil': typeof PerfilRoute
  '/registro': typeof RegistroRoute
  '/reportes': typeof ReportesRoute
  '/solicitudes': typeof SolicitudesRoute
  '/usuarios': typeof UsuariosRoute
  '/donaciones/$id': typeof DonacionesIdRoute
  '/donaciones/': typeof DonacionesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crear-donacion': typeof CrearDonacionRoute
  '/dashboard': typeof DashboardRoute
  '/empresas': typeof EmpresasRoute
  '/entregas': typeof EntregasRoute
  '/mis-donaciones': typeof MisDonacionesRoute
  '/mis-solicitudes': typeof MisSolicitudesRoute
  '/organizaciones': typeof OrganizacionesRoute
  '/perfil': typeof PerfilRoute
  '/registro': typeof RegistroRoute
  '/reportes': typeof ReportesRoute
  '/solicitudes': typeof SolicitudesRoute
  '/usuarios': typeof UsuariosRoute
  '/donaciones/$id': typeof DonacionesIdRoute
  '/donaciones': typeof DonacionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crear-donacion': typeof CrearDonacionRoute
  '/dashboard': typeof DashboardRoute
  '/empresas': typeof EmpresasRoute
  '/entregas': typeof EntregasRoute
  '/mis-donaciones': typeof MisDonacionesRoute
  '/mis-solicitudes': typeof MisSolicitudesRoute
  '/organizaciones': typeof OrganizacionesRoute
  '/perfil': typeof PerfilRoute
  '/registro': typeof RegistroRoute
  '/reportes': typeof ReportesRoute
  '/solicitudes': typeof SolicitudesRoute
  '/usuarios': typeof UsuariosRoute
  '/donaciones/$id': typeof DonacionesIdRoute
  '/donaciones/': typeof DonacionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crear-donacion'
    | '/dashboard'
    | '/empresas'
    | '/entregas'
    | '/mis-donaciones'
    | '/mis-solicitudes'
    | '/organizaciones'
    | '/perfil'
    | '/registro'
    | '/reportes'
    | '/solicitudes'
    | '/usuarios'
    | '/donaciones/$id'
    | '/donaciones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crear-donacion'
    | '/dashboard'
    | '/empresas'
    | '/entregas'
    | '/mis-donaciones'
    | '/mis-solicitudes'
    | '/organizaciones'
    | '/perfil'
    | '/registro'
    | '/reportes'
    | '/solicitudes'
    | '/usuarios'
    | '/donaciones/$id'
    | '/donaciones'
  id:
    | '__root__'
    | '/'
    | '/crear-donacion'
    | '/dashboard'
    | '/empresas'
    | '/entregas'
    | '/mis-donaciones'
    | '/mis-solicitudes'
    | '/organizaciones'
    | '/perfil'
    | '/registro'
    | '/reportes'
    | '/solicitudes'
    | '/usuarios'
    | '/donaciones/$id'
    | '/donaciones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrearDonacionRoute: typeof CrearDonacionRoute
  DashboardRoute: typeof DashboardRoute
  EmpresasRoute: typeof EmpresasRoute
  EntregasRoute: typeof EntregasRoute
  MisDonacionesRoute: typeof MisDonacionesRoute
  MisSolicitudesRoute: typeof MisSolicitudesRoute
  OrganizacionesRoute: typeof OrganizacionesRoute
  PerfilRoute: typeof PerfilRoute
  RegistroRoute: typeof RegistroRoute
  ReportesRoute: typeof ReportesRoute
  SolicitudesRoute: typeof SolicitudesRoute
  UsuariosRoute: typeof UsuariosRoute
  DonacionesIdRoute: typeof DonacionesIdRoute
  DonacionesIndexRoute: typeof DonacionesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear-donacion': {
      id: '/crear-donacion'
      path: '/crear-donacion'
      fullPath: '/crear-donacion'
      preLoaderRoute: typeof CrearDonacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregas': {
      id: '/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof EntregasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-donaciones': {
      id: '/mis-donaciones'
      path: '/mis-donaciones'
      fullPath: '/mis-donaciones'
      preLoaderRoute: typeof MisDonacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-solicitudes': {
      id: '/mis-solicitudes'
      path: '/mis-solicitudes'
      fullPath: '/mis-solicitudes'
      preLoaderRoute: typeof MisSolicitudesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizaciones': {
      id: '/organizaciones'
      path: '/organizaciones'
      fullPath: '/organizaciones'
      preLoaderRoute: typeof OrganizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitudes': {
      id: '/solicitudes'
      path: '/solicitudes'
      fullPath: '/solicitudes'
      preLoaderRoute: typeof SolicitudesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donaciones/': {
      id: '/donaciones/'
      path: '/donaciones'
      fullPath: '/donaciones/'
      preLoaderRoute: typeof DonacionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donaciones/$id': {
      id: '/donaciones/$id'
      path: '/donaciones/$id'
      fullPath: '/donaciones/$id'
      preLoaderRoute: typeof DonacionesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrearDonacionRoute: CrearDonacionRoute,
  DashboardRoute: DashboardRoute,
  EmpresasRoute: EmpresasRoute,
  EntregasRoute: EntregasRoute,
  MisDonacionesRoute: MisDonacionesRoute,
  MisSolicitudesRoute: MisSolicitudesRoute,
  OrganizacionesRoute: OrganizacionesRoute,
  PerfilRoute: PerfilRoute,
  RegistroRoute: RegistroRoute,
  ReportesRoute: ReportesRoute,
  SolicitudesRoute: SolicitudesRoute,
  UsuariosRoute: UsuariosRoute,
  DonacionesIdRoute: DonacionesIdRoute,
  DonacionesIndexRoute: DonacionesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
