import type { Donation, DonationRequest, Entity, User } from "./types";

export const seedEntities: Entity[] = [
  {
    id: "e1",
    nombre: "Grupo Alimentario Verde",
    tipo: "empresa",
    giro: "Distribución de alimentos",
    ciudad: "Ciudad de México",
    contacto: "logistica@gaverde.mx",
    estatus: "Verificada",
    desde: "2024-03-11",
  },
  {
    id: "e2",
    nombre: "Panificadora del Valle",
    tipo: "empresa",
    giro: "Panadería industrial",
    ciudad: "Puebla",
    contacto: "contacto@panvalle.mx",
    estatus: "Verificada",
    desde: "2024-07-02",
  },
  {
    id: "e3",
    nombre: "Supermercados Aurora",
    tipo: "empresa",
    giro: "Retail",
    ciudad: "Guadalajara",
    contacto: "donaciones@aurora.mx",
    estatus: "En revisión",
    desde: "2025-01-19",
  },
  {
    id: "o1",
    nombre: "Comedor Comunitario Esperanza",
    tipo: "organizacion",
    giro: "Comedor social",
    ciudad: "Ciudad de México",
    contacto: "esperanza@ong.mx",
    estatus: "Verificada",
    desde: "2023-11-08",
  },
  {
    id: "o2",
    nombre: "Fundación Manos Unidas",
    tipo: "organizacion",
    giro: "Asistencia alimentaria",
    ciudad: "Toluca",
    contacto: "hola@manosunidas.org",
    estatus: "Verificada",
    desde: "2024-05-21",
  },
  {
    id: "o3",
    nombre: "Casa Hogar San Miguel",
    tipo: "organizacion",
    giro: "Casa hogar",
    ciudad: "Querétaro",
    contacto: "contacto@sanmiguel.org",
    estatus: "En revisión",
    desde: "2025-02-14",
  },
];

export const seedUsers: User[] = [
  {
    id: "u1",
    nombre: "Laura Méndez",
    correo: "admin@donared.mx",
    rol: "admin",
    entidad: "DonaRed",
    entidadId: "sys",
    estado: "Activo",
    password: "demo1234",
  },
  {
    id: "u2",
    nombre: "Carlos Rivas",
    correo: "empresa@donared.mx",
    rol: "empresa",
    entidad: "Grupo Alimentario Verde",
    entidadId: "e1",
    estado: "Activo",
    password: "demo1234",
  },
  {
    id: "u3",
    nombre: "Ana Solís",
    correo: "org@donared.mx",
    rol: "organizacion",
    entidad: "Comedor Comunitario Esperanza",
    entidadId: "o1",
    estado: "Activo",
    password: "demo1234",
  },
  {
    id: "u4",
    nombre: "Miguel Torres",
    correo: "miguel@panvalle.mx",
    rol: "empresa",
    entidad: "Panificadora del Valle",
    entidadId: "e2",
    estado: "Activo",
  },
  {
    id: "u5",
    nombre: "Rocío Ibarra",
    correo: "rocio@manosunidas.org",
    rol: "organizacion",
    entidad: "Fundación Manos Unidas",
    entidadId: "o2",
    estado: "Activo",
  },
  {
    id: "u6",
    nombre: "Diego Fuentes",
    correo: "diego@aurora.mx",
    rol: "empresa",
    entidad: "Supermercados Aurora",
    entidadId: "e3",
    estado: "Inactivo",
  },
  {
    id: "u7",
    nombre: "Paula Ríos",
    correo: "paula@sanmiguel.org",
    rol: "organizacion",
    entidad: "Casa Hogar San Miguel",
    entidadId: "o3",
    estado: "Activo",
  },
];

export const seedDonations: Donation[] = [
  {
    id: "d1",
    nombre: "Despensas básicas familiares",
    descripcion: "Paquetes con arroz, frijol, aceite y pasta para familias de 4 personas.",
    categoria: "Alimentos no perecederos",
    cantidad: 120,
    unidad: "paquetes",
    vigencia: "2026-12-20",
    observaciones: "Requiere recolección en almacén central, horario de 9 a 17 h.",
    empresaId: "e1",
    empresaNombre: "Grupo Alimentario Verde",
    fecha: "2026-09-02",
    estado: "Disponible",
    historial: [{ estado: "Disponible", fecha: "2026-09-02", nota: "Donación publicada" }],
  },
  {
    id: "d2",
    nombre: "Pan de caja y bollería del día",
    descripcion: "Excedente diario de producción, apto para consumo inmediato.",
    categoria: "Alimentos frescos",
    cantidad: 60,
    unidad: "kg",
    vigencia: "2026-09-14",
    observaciones: "Debe recogerse el mismo día antes de las 20 h.",
    empresaId: "e2",
    empresaNombre: "Panificadora del Valle",
    fecha: "2026-09-08",
    estado: "Solicitada",
    historial: [
      { estado: "Disponible", fecha: "2026-09-08", nota: "Donación publicada" },
      { estado: "Solicitada", fecha: "2026-09-09", nota: "Solicitada por Fundación Manos Unidas" },
    ],
  },
  {
    id: "d3",
    nombre: "Leche entera 1 L",
    descripcion: "Cajas de leche con vigencia de tres meses.",
    categoria: "Bebidas",
    cantidad: 240,
    unidad: "litros",
    vigencia: "2026-11-30",
    observaciones: "Se entrega en tarimas completas.",
    empresaId: "e1",
    empresaNombre: "Grupo Alimentario Verde",
    fecha: "2026-08-28",
    estado: "Aprobada",
    historial: [
      { estado: "Disponible", fecha: "2026-08-28", nota: "Donación publicada" },
      { estado: "Solicitada", fecha: "2026-08-30", nota: "Solicitada por Comedor Esperanza" },
      { estado: "Aprobada", fecha: "2026-09-01", nota: "Solicitud aprobada por la empresa" },
    ],
  },
  {
    id: "d4",
    nombre: "Kits de higiene personal",
    descripcion: "Jabón, shampoo, pasta dental y cepillo.",
    categoria: "Higiene",
    cantidad: 80,
    unidad: "kits",
    vigencia: "2027-04-10",
    observaciones: "Ideal para albergues.",
    empresaId: "e3",
    empresaNombre: "Supermercados Aurora",
    fecha: "2026-08-20",
    estado: "En camino",
    historial: [
      { estado: "Disponible", fecha: "2026-08-20", nota: "Donación publicada" },
      { estado: "Solicitada", fecha: "2026-08-22", nota: "Solicitada por Casa Hogar San Miguel" },
      { estado: "Aprobada", fecha: "2026-08-24", nota: "Solicitud aprobada" },
      { estado: "En camino", fecha: "2026-09-05", nota: "Envío programado con transportista" },
    ],
  },
  {
    id: "d5",
    nombre: "Verdura de temporada",
    descripcion: "Zanahoria, calabaza y papa en costales de 20 kg.",
    categoria: "Alimentos frescos",
    cantidad: 300,
    unidad: "kg",
    vigencia: "2026-09-18",
    observaciones: "Producto de segunda calidad, apto para consumo.",
    empresaId: "e1",
    empresaNombre: "Grupo Alimentario Verde",
    fecha: "2026-08-10",
    estado: "Entregada",
    historial: [
      { estado: "Disponible", fecha: "2026-08-10", nota: "Donación publicada" },
      { estado: "Solicitada", fecha: "2026-08-11", nota: "Solicitada por Fundación Manos Unidas" },
      { estado: "Aprobada", fecha: "2026-08-12", nota: "Solicitud aprobada" },
      { estado: "En camino", fecha: "2026-08-13", nota: "Salida de almacén" },
      {
        estado: "Entregada",
        fecha: "2026-08-14",
        nota: "Recepción confirmada por la organización",
      },
    ],
  },
  {
    id: "d6",
    nombre: "Mobiliario de oficina",
    descripcion: "Sillas y escritorios en buen estado por renovación de mobiliario.",
    categoria: "Mobiliario",
    cantidad: 25,
    unidad: "piezas",
    vigencia: "2026-10-30",
    observaciones: "Se requiere transporte propio.",
    empresaId: "e2",
    empresaNombre: "Panificadora del Valle",
    fecha: "2026-08-05",
    estado: "Rechazada",
    historial: [
      { estado: "Disponible", fecha: "2026-08-05", nota: "Donación publicada" },
      { estado: "Solicitada", fecha: "2026-08-06", nota: "Solicitada por Casa Hogar San Miguel" },
      { estado: "Rechazada", fecha: "2026-08-07", nota: "Sin capacidad de traslado disponible" },
    ],
  },
  {
    id: "d7",
    nombre: "Cuadernos y útiles escolares",
    descripcion: "Material escolar nuevo de fin de temporada.",
    categoria: "Insumos escolares",
    cantidad: 150,
    unidad: "kits",
    vigencia: "2027-01-15",
    observaciones: "Prioridad para programas educativos.",
    empresaId: "e3",
    empresaNombre: "Supermercados Aurora",
    fecha: "2026-09-06",
    estado: "Disponible",
    historial: [{ estado: "Disponible", fecha: "2026-09-06", nota: "Donación publicada" }],
  },
];

export const seedRequests: DonationRequest[] = [
  {
    id: "r1",
    donacionId: "d2",
    donacionNombre: "Pan de caja y bollería del día",
    orgId: "o2",
    orgNombre: "Fundación Manos Unidas",
    empresaId: "e2",
    empresaNombre: "Panificadora del Valle",
    mensaje: "Atendemos 180 personas diarias, podemos recoger hoy mismo.",
    fecha: "2026-09-09",
    estado: "Pendiente",
  },
  {
    id: "r2",
    donacionId: "d3",
    donacionNombre: "Leche entera 1 L",
    orgId: "o1",
    orgNombre: "Comedor Comunitario Esperanza",
    empresaId: "e1",
    empresaNombre: "Grupo Alimentario Verde",
    mensaje: "La leche se destinará al desayuno infantil.",
    fecha: "2026-08-30",
    estado: "Aprobada",
  },
  {
    id: "r3",
    donacionId: "d4",
    donacionNombre: "Kits de higiene personal",
    orgId: "o3",
    orgNombre: "Casa Hogar San Miguel",
    empresaId: "e3",
    empresaNombre: "Supermercados Aurora",
    mensaje: "Tenemos 45 niñas y niños en el albergue.",
    fecha: "2026-08-22",
    estado: "En camino",
  },
  {
    id: "r4",
    donacionId: "d5",
    donacionNombre: "Verdura de temporada",
    orgId: "o2",
    orgNombre: "Fundación Manos Unidas",
    empresaId: "e1",
    empresaNombre: "Grupo Alimentario Verde",
    mensaje: "Contamos con cámara fría para conservar el producto.",
    fecha: "2026-08-11",
    estado: "Entregada",
  },
  {
    id: "r5",
    donacionId: "d6",
    donacionNombre: "Mobiliario de oficina",
    orgId: "o3",
    orgNombre: "Casa Hogar San Miguel",
    empresaId: "e2",
    empresaNombre: "Panificadora del Valle",
    mensaje: "Necesitamos mobiliario para el área de tareas.",
    fecha: "2026-08-06",
    estado: "Rechazada",
  },
  {
    id: "r6",
    donacionId: "d1",
    donacionNombre: "Despensas básicas familiares",
    orgId: "o1",
    orgNombre: "Comedor Comunitario Esperanza",
    empresaId: "e1",
    empresaNombre: "Grupo Alimentario Verde",
    mensaje: "Solicitamos 40 paquetes para entrega semanal.",
    fecha: "2026-09-07",
    estado: "Pendiente",
  },
];

export const seedActivity = [
  { texto: "Grupo Alimentario Verde publicó “Despensas básicas familiares”", fecha: "2026-09-02" },
  {
    texto: "Fundación Manos Unidas solicitó “Pan de caja y bollería del día”",
    fecha: "2026-09-09",
  },
  { texto: "Supermercados Aurora marcó “Kits de higiene personal” en camino", fecha: "2026-09-05" },
  { texto: "Comedor Esperanza confirmó recepción de “Verdura de temporada”", fecha: "2026-08-14" },
];

export const monthlyStats = [
  { mes: "Abr", donaciones: 12, entregas: 9 },
  { mes: "May", donaciones: 18, entregas: 14 },
  { mes: "Jun", donaciones: 22, entregas: 17 },
  { mes: "Jul", donaciones: 27, entregas: 21 },
  { mes: "Ago", donaciones: 31, entregas: 26 },
  { mes: "Sep", donaciones: 36, entregas: 29 },
];
